spring:
  application:
    name: spring-boot-sample
  # mycat http://blog.csdn.net/wang_jingj/article/details/54091898
  datasource:
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://117.48.202.155:8066/jhipster_monolithic_sample?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 654321
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
#  resources: 
#    add-mappings: false
  data: 
    elasticsearch:
      cluster-name: elasticsearch_cluster
      cluster-nodes: 117.48.202.155:9300
      properties:
        path: 
          logs: ./elasticsearch/log #elasticsearch日志存储目录
          data: ./elasticsearch/data #elasticsearch数据存储目录